"""Optional LLM commentary on a report (F5.5).

Reuses the M2 :class:`~quantlab.dsl.llm.LLMClient` protocol, so commentary is
generated by the same pluggable client (real Anthropic, or a fake in tests). The
prompt hands the model only the computed numbers and integrity verdicts and asks
for an honest, non-promotional interpretation — it must not oversell a strategy
the integrity checks flagged.
"""

from __future__ import annotations

from quantlab.dsl.llm import LLMClient
from quantlab.report.report import ReportInputs

_SYSTEM = """You are a skeptical quant research assistant. Given a backtest's
metrics and research-integrity verdicts, write 2-4 plain sentences interpreting
the result for the researcher. Be honest: if the shuffle control says DISCARD or
PBO indicates overfitting, say the result is not trustworthy regardless of a high
Sharpe. Do not promote or give investment advice. No preamble."""


def _facts(inp: ReportInputs) -> str:
    s = inp.stats
    lines = [
        f"strategy: {inp.label}",
        f"CAGR {s['cagr']:.1%}, Sharpe {s['sharpe']:.2f}, "
        f"max drawdown {s['max_drawdown']:.1%}, cost drag {s.get('cost_drag', 0):.2%}",
    ]
    if inp.shuffle is not None:
        verdict = "SURVIVES" if inp.shuffle.survives else "DISCARD"
        lines.append(f"shuffle control: p={inp.shuffle.p_value:.3f} [{verdict}]")
    if inp.pbo is not None:
        lines.append(f"PBO: {inp.pbo.pbo:.2f} [{'OVERFIT' if inp.pbo.overfit else 'OK'}]")
    if inp.dsr is not None:
        lines.append(f"Deflated Sharpe (P[SR>0]): {inp.dsr:.2f}")
    if inp.ml is not None:
        lines.append(f"OOS Rank IC {inp.ml['rank_ic_mean']:+.3f}, IC IR {inp.ml['ic_ir']:+.2f}")
    return "\n".join(lines)


def generate_commentary(client: LLMClient, inp: ReportInputs) -> str:
    """Return an LLM-written interpretation of the report (plain text)."""
    return client.complete(_SYSTEM, _facts(inp)).strip()
